### ISSUE TITLE
[Bug]: Statuses stuck on Triggered due to Sensor Problem panel status + Sensors Info/Sensors Status Blank Response

### ISSUE THREAD

**Issue by sapireli** [mrjackyliang/homebridge-adt-pulse#128] opened 2024-01-17 02:42 UTC
### Pre-check confirmation

- [X] I have provided a descriptive title for the bug I am having
- [X] I have kept the original title prefix, __"[Bug]: "__
- [X] I have done my research, and this is __NOT__ a duplicate bug report
- [X] I am __NOT__ requesting a new feature
- [X] I am using the latest version of the plugin

### Your email address

eli@vcboy.com

### Tell us exactly what happened

@mrjackyliang Sorry for the delay, I had a bunch of family over this weekend. I updated to the 3.0 release and the issue remains panel status in homebridge/homekit is still triggered.

attached is the html from the summary page:
[summary.html.txt](https://github.com/mrjackyliang/homebridge-adt-pulse/files/13957973/summary.html.txt)

### Plugin version

3.0

### Homebridge version

1.7

### Node.js® version

18.19

### Log output of the `test-api` command

```Shell
-
```

### More logs relevant to this bug

```Shell
-
```

### Legal Agreements

- [X] I agree to the Terms of Use and Privacy Policy

**Comment by mrjackyliang** [comment] 2024-01-17 02:49
Can you try running the `test-api` command? I've been receiving random empty array requests, sometimes it is the `sensorsInfo` being empty, sometimes it is the `sensorsStatus` being empty.

And it happens so randomly as well.

**Comment by mrjackyliang** [comment] 2024-01-18 16:35
I published `v3.0.1` to further try to debug this issue.

**Comment by sapireli** [comment] 2024-01-18 18:01
Thank you so much, just installed it. Will run the test-api tonight and revert

**Comment by mrjackyliang** [comment] 2024-01-18 23:52
Also, can you send your Homebridge statuses as a screenshot and a list of your system specs? I'm not getting any information that the sensors are empty on the portal. If it comes back as an empty array, my next assumption would be do you have enough memory.

**Comment by mrjackyliang** [comment] 2024-01-19 00:15
Also, are you seeing these warnings in the logs (assuming you added sensors into your config)?

- `Changes to sensors information cannot be determined due to length inconsistencies.`
- `Changes to sensors status cannot be determined due to length inconsistencies.`

**Comment by mrjackyliang** [comment] 2024-01-19 00:21
Check to also see if setting the operational speed to the slowest mode, see if that helps.

**Comment by mrjackyliang** [comment] 2024-01-19 19:17
Updated the plugin to `v3.0.4`

**Comment by mrjackyliang** [comment] 2024-01-20 17:30
I've gotten another notice. This time `sensorsStatus` is populated, but `sensorsInfo` isn't.

Try running this on a platform with more CPU and memory. Doesn't seem like an implementation issue now that I see it flowing.

**Comment by sapireli** [comment] 2024-01-23 06:31
hey @mrjackyliang again sorry for delay here.

I tried investigating the issue where the panel status is incorrectly reported as triggered, and I believe i figured out the root cause is the isPanelAlarmActive function in utility.ts.

The function currently considers 'Sensor Problem' and 'Sensor Problems' as conditions that indicate an active alarm:
`export function isPanelAlarmActive(panelStatuses: IsPanelAlarmActivePanelStatuses): IsPanelAlarmActiveReturns {
  return (
    panelStatuses.includes('BURGLARY ALARM')
    || panelStatuses.includes('Carbon Monoxide Alarm')
    || panelStatuses.includes('FIRE ALARM')
    **|| panelStatuses.includes('Sensor Problem')
    || panelStatuses.includes('Sensor Problems')**
    || panelStatuses.includes('Uncleared Alarm')
    || panelStatuses.includes('WATER ALARM')
  );
}`

in my case, a low battery on one of the sensors was causing a 'Sensor Problem' status, which should not be treated as an active alarm. This misinterpretation seems to have led to the system being reported as always triggered.

**I removed the lines that check for 'Sensor Problem' and 'Sensor Problems'** from the isPanelAlarmActive function, and the **issue resolved**.

I just wanted to share it with you before making a pull request because I'm unsure of the broader implications this change might have on other parts of the system or for other users etc...what do you think? I'm sure you had some reasoning for the implementation that I'm just not aware of.

**Comment by mrjackyliang** [comment] 2024-01-23 12:33
Sensor Problem and Sensor Problems are considered active alarms from the way how I tested them.

The alarm was actually ringing at the time I force tampered with a sensor. But that still doesn't explain the fact that sometimes your sensors don't update. Those are two separate issues.

**Comment by sapireli** [comment] 2024-01-23 16:25
Thank you 🙏. It seems like some sensors problems are not alarm triggers. For example, opening up a contact sensor which triggers the temper switch inside causes a sensor problem but doesn’t trigger the alarm if it’s not armed. I just tested this. What type sensor did you temper with to trigger? 

Curious thing with the sensors not updating. They actually are updating well but in the logs I see messages like

‘’’
[1/23/2024, 11:10:05 AM] [ADT Pulse] undefined state changed (old: "Motion", new: "No Motion").
[1/23/2024, 11:10:33 AM] [ADT Pulse] undefined state changed (old: "Open", new: "Closed").
[1/23/2024, 11:10:33 AM] [ADT Pulse] undefined state changed (old: "Motion", new: "No Motion").
[1/23/2024, 11:10:58 AM] [ADT Pulse] undefined state changed (old: "Motion", new: "No Motion").
[1/23/2024, 11:11:43 AM] [ADT Pulse] undefined state changed (old: "Motion", new: "No Motion").
‘’’

but even when these are logged the actual motion sensor being tripped shows up correctly as triggered in the accessories tab/home app. Weird.

also I don’t see any of these in the logs:
 Changes to sensors information cannot be determined due to length inconsistencies.
Changes to sensors status cannot be determined due to length inconsistencies.

**Comment by sapireli** [comment] 2024-01-23 17:26
Just emailed you thank you

**Comment by mrjackyliang** [comment] 2024-01-23 18:15
Yep, can confirm the sensors status missing is from your device.

**Comment by mrjackyliang** [comment] 2024-01-24 14:16
Can you confirm that the sensor issue only happens when you start up the device?

If it is and your sensors are properly showing, I can at safely make some simple changes and put this to rest.

**Comment by mrjackyliang** [comment] 2024-01-25 20:38
So after I tested the system sensor by pulling out the battery and triggering the Sensor Problem status, it didn't matter how I tried to disarm the system, the Disarm won't ever go away until I fix the issue.

So the Sensor Problem status is valid, even if the system isn't ringing. I believe this issue needs to either be fixed by having ADT come to your home and resolve it, or if you are adventurous, you can read the manual to the alarm panel system (I tried doing that one day, but I couldn't even comprehend what was inside yet) and remove the non-working devices yourself.

**Comment by mrjackyliang** [comment] 2024-01-25 20:39
Just for reference, this is how the system looks like when there is a sensor problem:

<img width="418" alt="Screenshot 2024-01-25 at 3 39 16 PM" src="https://github.com/mrjackyliang/homebridge-adt-pulse/assets/9779803/2da87607-30fe-4773-b65c-85fb9cf44bfd">

**Comment by mrjackyliang** [comment] 2024-01-25 20:58
In the meantime, I'll close this issue off since it is considered invalid, but I'll keep it in mind and think about how to define this edge case better.

**Comment by mrjackyliang** [comment] 2024-01-26 18:29
Currently working on implementing an `options` configuration. Should be up in the next `v3.1.0` update.

**Comment by sapireli** [comment] 2024-01-27 04:23
@mrjackyliang first off you are the man. Thank you for spending so much time on this. 

In terms of the triggered/sensor problem: how hard would it be to exclude the “low battery” edge case.  “Low battery” sensor status shows up as a sensor problem on the pulse dashboard like in your screenshot but doesn’t ring on the panel or require any immediate action from the user. This is what’s causing my issue. 

interestingly, my dashboard doesn’t show the “security panel trouble: check security keypad” highlighted message. Although it does show sensor problem. Maybe that’s the only distinction between the low battery and other sensor problems. Screenshot below:
![IMG_9588](https://github.com/mrjackyliang/homebridge-adt-pulse/assets/114778791/219fc0ff-50c2-4f1b-87f1-f8b41647382b)

Otherwise the other sensor problems like tampering are behaving correctly.

**Comment by mrjackyliang** [comment] 2024-01-27 04:40
I'm not sure if it makes sense to have an `ignoreLowBatteryStatus` option because at the end, even if you ignore it, it's not like the panel statuses would go back to "All Quiet".

The panel status is very vague in this sense, now that I see what your summary page looks like, it could be
- A sensor problem, with no alarm
- A sensor problem, with the alarm constantly beeping
- In the case here, things like low battery

If I don't put the "Sensor Problem" part of an active alarm, the user won't be able to turn the alarm off, when it's indeed, ringing.

This one's a bit tricky because I don't expose the button context into Homebridge.

**Comment by sapireli** [comment] 2024-01-27 04:50
What is was thinking is if the dashboard shows “sensor problem” but the  “check security keypad” message doesn’t show then perhaps alarm shouldn’t be “triggered”

on unrelated note 3.1 isn’t working for me throws this error:
‘’’
[1/26/2024, 11:41:05 PM] [ADT Pulse] If you just upgraded from v2 to v3 / v3.1, please update your configuration structure.
[
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "options"
    ],
    "message": "Required"
  }
]’’’

went back to 3.0.6 no error.

**Comment by mrjackyliang** [comment] 2024-01-27 05:04
It's because the config is missing the new `options` config. Should be in the notices before you click upgrade.

**Comment by mrjackyliang** [comment] 2024-01-27 05:05
> What is was thinking is if the dashboard shows “sensor problem” but the “check security keypad” message doesn’t show then perhaps alarm shouldn’t be “triggered”

If that's the case, I need to question when would this message show? Just more scenarios to deal with without being able to 100% confirm that it's true.

**Comment by sapireli** [comment] 2024-01-27 05:13
That’s a good point. How hard would it be to implement ignoreLowBatteryStatus

just saw the note and upgrading again. 👍🙏

**Comment by mrjackyliang** [comment] 2024-01-27 05:30
Wouldn't be hard, but it wouldn't fix the issue that you're having because they aren't related at all.

**Comment by sapireli** [comment] 2024-01-27 05:30
Nevermind my last comment, the way it’s implemented in 3.1 is perfect. Thank you 🙏 get some rest from all of this. You crushed it.

**Comment by mrjackyliang** [comment] 2024-01-27 08:30
Continuing to document this further:

- Sensor Problem can be an issue as small as a Low Battery status. This should not consist of an active alarm.
- Sensor Problem with Disarm, Arm Away, and Arm Stay button should consist of an active alarm (even if the alarm panel is ringing or not).

@sapireli TODO: Need to find out what kind of buttons are available during Arm Stay, Arm Away, and Arm Night. I'm hoping it's just the one (Disarm button), so I can make this check permanent and allow you to silence the alarm when an actual Sensor Problem happens (pulling off battery cover and such).

**Comment by gabesean** [comment] 2024-02-11 20:55
@mrjackyliang First off, thank you and the contributors for all the hard work into developing this plugin which I’ve happily used for years now. 🙂 

Also, thank you for reopening this issue as I am experiencing something very similar as what has been discussed on this thread. After being on `v2` for so long, I just decided to jump to the latest `v3.1.2`.

My current issues on HomeKit are:

- Critical Triggered notification & status on “Away”, “Home”, “Off” (all states)

Current issues on the Pulse portal:

- “Security Panel Trouble: Check Security Keypad”
- Two offline devices (due to low battery)

Current issues on the keypad:

- Two devices (zones) with the “Device Low Battery" message
- “Device Fault” > “Zone Fault” shows the same two zones as the two devices with low battery

### Plugin version

`3.1.2`

### Homebridge version

`1.7.0`

### Node.js® version

`18.13.0`



I really appreciate this plugin but due to the issue within HomeKit, I have had to disable this plugin temporarily which is quite unfortunate. Is there a way to configure the plugin to disregard these messages as they really shouldn’t be considered “Critical” in HomeKit? `v2` did not give me this issue. It scared me as I thought I triggered the alarm by mistake haha!

Would you like any more info from my end to debug this? Thank you again.

**Comment by mrjackyliang** [comment] 2024-02-11 21:00
> @mrjackyliang First off, thank you and the contributors for all the hard work into developing this plugin which I’ve happily used for years now. 🙂
> 
> Also, thank you for reopening this issue as I am experiencing something very similar as what has been discussed on this thread. After being on `v2` for so long, I just decided to jump to the latest `v3.1.2`.
> 
> My current issues on HomeKit are:
> 
> * Critical Triggered notification & status on “Away”, “Home”, “Off” (all states)
> 
> Current issues on the Pulse portal:
> 
> * “Security Panel Trouble: Check Security Keypad”
> * Two offline devices (due to low battery)
> 
> Current issues on the keypad:
> 
> * Two devices (zones) with the “Device Low Battery" message
> * “Device Fault” > “Zone Fault” shows the same two zones as the two devices with low battery
> 
> ### Plugin version
> `3.1.2`
> 
> ### Homebridge version
> `1.7.0`
> 
> ### Node.js® version
> `18.13.0`
> 
> I really appreciate this plugin but due to the issue within HomeKit, I have had to disable this plugin temporarily which is quite unfortunate. Is there a way to configure the plugin to disregard these messages as they really shouldn’t be considered “Critical” in HomeKit? `v2` did not give me this issue. It scared me as I thought I triggered the alarm by mistake haha!
> 
> Would you like any more info from my end to debug this? Thank you again.

@gabesean At the moment, you can read this [section](https://github.com/mrjackyliang/homebridge-adt-pulse?tab=readme-ov-file#specifying-advanced-options) in the readme to temporarily ease this issue. This is a temporary workaround, haven't gotten to fixing the actual bug yet, but this should work.

**Comment by gabesean** [comment] 2024-02-12 07:40
Thank you, yes that eases the issue for now!

**Comment by mrjackyliang** [comment] 2024-02-17 00:43
I made an update to document the set of security buttons from your portal. Please update!

**Comment by sapireli** [comment] 2024-02-17 19:47
@mrjackyliang tested 3.1.5 when I uncheck ignoreSensorProblemStatus it indeed doesn’t show alarm as triggered, but sensors stop updating and alarm is unable to arm. Checking it again and restarting the bridge restores function.

**Comment by mrjackyliang** [comment] 2024-02-17 19:48
> @mrjackyliang tested 3.1.5 when I uncheck ignoreSensorProblemStatus it indeed doesn’t show alarm as triggered, but sensors stop updating and alarm is unable to arm. Checking it again and restarting the bridge restores function.

@sapireli The bug isn't fixed yet, weird why it doesn't show the alarm as triggered for you anymore.

**Comment by mrjackyliang** [comment] 2024-02-19 01:39
I released `v3.2.0`. Should fix the Sensor Problem status now. However, if the system refuses to let you disarm, the triggered status will continue to show until the problem can be remedied (like tampering with a sensor).

**Comment by sapireli** [comment] 2024-02-19 02:22
Thank you @mrjackyliang with 3.2.0 same issue as before though - whne i uncheck ignoreSensorProblemStatus unable to disarm/arm and sensors stop updating, everything works well when its checked

**Comment by mrjackyliang** [comment] 2024-02-19 02:51
> Thank you @mrjackyliang with 3.2.0 same issue as before though - whne i uncheck ignoreSensorProblemStatus unable to disarm/arm and sensors stop updating, everything works well when its checked

@sapireli Can I see your ADT Pulse summary page again?

**Comment by sapireli** [comment] 2024-02-19 02:55
@mrjackyliang in your inbox

**Comment by mrjackyliang** [comment] 2024-02-19 03:54
> @mrjackyliang in your inbox

@sapireli I've checked, the code seems like it's doing what it need to do. But to make sure, replace this file located in `./build/lib`, restart Homebridge, and check the logs for additional output.

[utility.js.zip](https://github.com/mrjackyliang/homebridge-adt-pulse/files/14326102/utility.js.zip)

**Comment by mrjackyliang** [comment] 2024-04-02 16:05
@sapireli I have gone back to revise this issue. It seems like on your recent summary page from the previous version, a Disarm button is showing.

This may be causing the ringing status to continuously show as the fix I confirmed today is indeed correct.

**Closed by mrjackyliang** 2024-04-02 16:05 UTC
Labels: bug

**Comment by mrjackyliang** [comment] 2024-04-02 16:27
I was planning to remove the "ignoreSensorProblemStatus" override, but it seems like it can be a permanent issue for some systems, so I'll keep this workaround intact.
