### ISSUE TITLE
Web portal logging out after login (system could be undergoing maintenance)

### ISSUE THREAD

**Issue by Rkell123** [mrjackyliang/homebridge-adt-pulse#144] opened 2024-04-22 04:04 UTC
### Pre-check confirmation

- [X] I am currently sponsoring you or have heavily contributed to this project.
- [X] I have kept the original title prefix, __"[Support]: "__

### Tell me exactly what happened

I have not been able to use the plugin in quite some time. This is the current error
[4/21/2024, 8:53:21 PM] [ADT Pulse] Login attempt has failed. Trying 2 more times ...
{
  action: 'LOGIN',
  success: false,
  info: {
    message: '"/myhome/28.0.0-57/access/signin.jsp?e=ns&partner=adt" is not the summary page'
  }
}
[4/21/2024, 8:53:23 PM] [ADT Pulse] Login attempt has failed. Trying 1 more time ...
{
  action: 'LOGIN',
  success: false,
  info: {
    message: '"/myhome/28.0.0-57/access/signin.jsp?e=ns&partner=adt" is not the summary page'
  }
}
[4/21/2024, 8:53:24 PM] [ADT Pulse] Login attempt has failed for 3 times. Sleeping for 30 minutes before resuming ...
{
  action: 'LOGIN',
  success: false,
  info: {
    message: '"/myhome/28.0.0-57/access/signin.jsp?e=ns&partner=adt" is not the summary page'
  }
}

### Logs relevant to this issue

```Shell
[4/21/2024, 8:53:21 PM] [ADT Pulse] Login attempt has failed. Trying 2 more times ...
{
  action: 'LOGIN',
  success: false,
  info: {
    message: '"/myhome/28.0.0-57/access/signin.jsp?e=ns&partner=adt" is not the summary page'
  }
}
[4/21/2024, 8:53:23 PM] [ADT Pulse] Login attempt has failed. Trying 1 more time ...
{
  action: 'LOGIN',
  success: false,
  info: {
    message: '"/myhome/28.0.0-57/access/signin.jsp?e=ns&partner=adt" is not the summary page'
  }
}
[4/21/2024, 8:53:24 PM] [ADT Pulse] Login attempt has failed for 3 times. Sleeping for 30 minutes before resuming ...
{
  action: 'LOGIN',
  success: false,
  info: {
    message: '"/myhome/28.0.0-57/access/signin.jsp?e=ns&partner=adt" is not the summary page'
  }
}
```

### Legal Agreements

- [X] I agree to the Terms of Use and Privacy Policy

**Comment by mrjackyliang** [comment] 2024-04-23 01:19
Sorry for the delay. Will investigate this issue soon!

**Comment by Rkell123** [comment] 2024-04-23 01:24
Thank youIt’s very likely I’m just an idiot….Sorry to be a bother and thank you for making everything work all the time!CheersRyanSent from my iPhoneOn Apr 22, 2024, at 6:19 PM, Jacky Liang ***@***.***> wrote:﻿
Sorry for the delay. Will investigate this issue soon!

**Comment by mrjackyliang** [comment] 2024-04-25 17:27
Is the login error always the case? It seems only happening for some users.

**Comment by Rkell123** [comment] 2024-04-25 17:57
For me yes, but to be honest, I don’t have a chan e to go and look at logs often as we have 3 kids…. I was just able to look this time and send this as they al somehow went to sleep at a decent time…..

**Comment by mrfatboy** [comment] 2024-06-27 09:51
I just updated to the latest version of the plugin and now I'm getting this error also. I tried deleting the plugin and rebuilding the configuration from scratch with fingerprint. 

Any ideas what to try next?

**Comment by mrjackyliang** [comment] 2024-06-27 11:08
I'm sure it's a minor issue, will be working on it at the end of next month. Apologize for the delays, life got ahead of me.

**Comment by Danimal4326** [comment] 2024-07-29 05:32
I just started getting this as well. 
I notice logging into https://portal.adtpulse.com/ in a browser, it logs in, but after a few seconds, it shows the login page again.

**Comment by mrjackyliang** [comment] 2024-07-29 05:37
Going to investigate this tomorrow morning. Got like an influx of anomaly notifications lately with not being able to get sensors information

**Comment by mrjackyliang** [comment] 2024-07-29 06:13
I'm actually getting the same kind of errors, just by trying to login in the browser. 90% of the time I am being redirected back to the login page. I suspect this is the ADT Pulse website, not the plugin itself.

Because the errors are saying, the expected URL is the summary page URL, but the login page URL was detected instead.

**Comment by Danimal4326** [comment] 2024-07-29 06:16
I'm thinking the same thing.  
I turned off my plugin in Homebridge for now.  I'll try website in the morning and see if it improves.

**Comment by mrjackyliang** [comment] 2024-07-29 06:16
I hope they aren't affected by Crowdstrike too🤣

**Comment by mrjackyliang** [comment] 2024-07-29 13:40
Looks like the issue is gone. It is just system maintenance. I'm going to think this is typical, and not much of a bug.

It's a human caused issue at the end (in its most unsuspecting ways), will make a UX improvement attempt. For now, closing this issue.

**Closed by mrjackyliang** 2024-07-29 13:40 UTC
Labels: question

**Comment by mrfatboy** [comment] 2024-08-01 20:31
I'm still getting this issue.
![Capture](https://github.com/user-attachments/assets/98caf8da-7915-4a97-b34b-245a29730d36)

**Comment by mrjackyliang** [comment] 2024-08-01 21:16
> I'm still getting this issue. ![Capture](https://private-user-images.githubusercontent.com/3344008/354374462-98caf8da-7915-4a97-b34b-245a29730d36.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NDcyMTIsIm5iZiI6MTcyMjU0NjkxMiwicGF0aCI6Ii8zMzQ0MDA4LzM1NDM3NDQ2Mi05OGNhZjhkYS03OTE1LTRhOTctYjM0Yi0yNDVhMjk3MzBkMzYuSlBHP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDFUMjExNTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmEwMDM0NDJmZmUwNzNkMmRiZTY0NDc1MDQzY2Y1NWRlODRlYmQwZTJjYmZiZTY4ZDExMTc0MTEyNDZkM2I2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xVs59qYzaUUE7VtQHPB3zwc451E3EVRUTZ3X-w6juIw)

Your issue isn't related to undergoing maintenance. It seems like your IP is blocked by the web portal. Double check if you can access the portal using a web browser.

**Comment by Rkell123** [comment] 2024-08-17 06:41
I am unable to login still even with the new version Can login to the portal just fine, keep getting an error saying check logsLogs say user name and or password incorrect, but they areCheersRyanSent from my iPhoneOn Aug 1, 2024, at 2:16 PM, Jacky Liang ***@***.***> wrote:﻿

I'm still getting this issue. 

Your issue isn't related to undergoing maintenance. It seems like your IP is blocked by the web portal. Double check if you can access the portal using a web browser.

**Comment by mrfatboy** [comment] 2024-08-17 09:05
Try logging into adt pulse via a web browser. Go into your account settings and clear all trusted computers. Log out. 

Now follow the GitHub instructions for getting new fingerprint and setting up the account in the plugin. 

Hopefully that fixes the issue.

**Comment by mrjackyliang** [comment] 2024-08-17 11:41
I'm going to work on improvements today see what I can come up with. However, clearing up all your trusted devices first will work since the setup wizard does not use old fingerprints.

**Comment by mrjackyliang** [comment] 2024-08-17 15:09
I've made some improvements to the error message you are seeing. Apparently the invalid username/password error message is hard-coded. Will work on finalizing the new settings page and hopefully, will be able to release it tonight or tomorrow.
