### ISSUE TITLE
Login Failed because Response Path is undefined (OpenSSL v1.1.1 and 1024-bit DH key)

### ISSUE THREAD

**Issue by superfeldy** [mrjackyliang/homebridge-adt-pulse#2] opened 2019-10-14 23:58 UTC
[ADT-Pulse] Login failed more than once. Portal sync terminated.

Whenever plugin is activated.

**Comment by mrjackyliang** [comment] 2019-10-15 01:00
What website do you use to login to the ADT Pulse Web Portal?

**Comment by superfeldy** [comment] 2019-10-15 01:12
https://portal.adtpulse.com/

**Comment by mrjackyliang** [comment] 2019-10-15 01:14
Set the `logLevel` setting to 40, disable all other plugins and then send the logs here.

**Comment by superfeldy** [comment] 2019-10-15 01:17
Ok. Will do when I get back to the system.

**Comment by mrjackyliang** [comment] 2019-10-15 01:29
Thanks! I suspect it might be the special characters in the password.

**Comment by superfeldy** [comment] 2019-10-17 06:54
Here you go:

[Homebridge] [10/16/2019, 11:53:10 PM] Loaded config.json with 0 accessories and 1 platforms.
[Homebridge] [10/16/2019, 11:53:10 PM] ---
[Homebridge] [10/16/2019, 11:53:11 PM] Loaded plugin: homebridge-adt-pulse
[Homebridge] [10/16/2019, 11:53:11 PM] Registering platform 'homebridge-adt-pulse.ADTPulse'
[Homebridge] [10/16/2019, 11:53:11 PM] ---
[Homebridge] [10/16/2019, 11:53:11 PM] Loading 1 platforms...
[Homebridge] [10/16/2019, 11:53:11 PM] [ADT-Pulse] Initializing ADTPulse platform...
[Homebridge] [10/16/2019, 11:53:11 PM] Loading 0 accessories...
[Homebridge] X-HM://0023ISYWY4P3G
[Homebridge] [10/16/2019, 11:53:11 PM] [ADT-Pulse] Cached accessories loaded...
[Homebridge] [10/16/2019, 11:53:11 PM] Service is running on port 51826.
[Homebridge] ADT Pulse: Logging in...
[Homebridge] ADT Pulse: Response path -> undefined
[Homebridge] ADT Pulse: Response path matches -> false
[Homebridge] ADT Pulse: Login failed.
[Homebridge] [10/16/2019, 11:53:11 PM] [ADT-Pulse] Login failed. Trying again.
[Homebridge] ADT Pulse: Logging in...
[Homebridge] ADT Pulse: Response path -> undefined
[Homebridge] ADT Pulse: Response path matches -> false
[Homebridge] ADT Pulse: Login failed.
[Homebridge] [10/16/2019, 11:53:15 PM] [ADT-Pulse] Login failed more than once. Portal sync terminated.
[Homebridge] ADT Pulse: Logging in...
[Homebridge] ADT Pulse: Response path -> undefined
[Homebridge] ADT Pulse: Response path matches -> false
[Homebridge] ADT Pulse: Login failed.
[Homebridge] [10/16/2019, 11:53:19 PM] [ADT-Pulse] Login failed more than once. Portal sync terminated.

**Comment by mrjackyliang** [comment] 2019-10-17 11:25
Wow, that's extremely weird. Can I ask what version of `node` and what version of `homebridge` are you running?

**Comment by superfeldy** [comment] 2019-10-19 20:42
I’m using node v10.16.3
And as far as Homebridge I’m using Hoobs.

**Comment by adamsinger** [comment] 2019-10-22 01:45
I am having a similar issue. As an experiment I changed my password to only contain numbers and letters, and it still fails. I can log into https://portal.adtpulse.com just fine.

Running Homebridge v0.4.50
Running Node v10.16.1

```
Oct 21 18:41:57 raspberrypi homebridge[1424]: [10/21/2019, 6:41:57 PM] [ADT-Pulse] Login failed. Trying again.
Oct 21 18:41:59 raspberrypi homebridge[1424]: ADT Pulse: Logging in...
Oct 21 18:42:00 raspberrypi homebridge[1424]: ADT Pulse: Response path -> undefined
Oct 21 18:42:00 raspberrypi homebridge[1424]: ADT Pulse: Response path matches -> false
Oct 21 18:42:00 raspberrypi homebridge[1424]: ADT Pulse: Login failed.
Oct 21 18:42:00 raspberrypi homebridge[1424]: [10/21/2019, 6:42:00 PM] [ADT-Pulse] Login failed more than once. Portal sync terminated.
```

**Comment by mrjackyliang** [comment] 2019-10-22 02:44
@superfeldy Thanks for the information. I assume Hoobs is also a device that runs similar to Raspberry Pi just like how @adamsinger mentioned.

I just got back from vacation, so sorry for the late reply. As far as the response path being `undefined`, I think the problem is isolated to devices of a particular Linux distro. I'm currently running `GNU/Linux`.

If you can do me a favor and run the following command in Homebridge then paste the response in this thread, that would be awesome. This allows me to figure out which operating system you are running under since I suspect the `undefined` issue is caused by incompatibility.
```
uname -a
```

**Comment by superfeldy** [comment] 2019-10-22 03:49
Yes it it. 
The response is: 
Linux hoobs 4.19.58-v7l+ #1245 SMP Fri Jul 12 17:31:45 BST 2019 armv7l GNU/Linux

**Comment by adamsinger** [comment] 2019-10-22 15:40
Mine was:

```
Linux raspberrypi 4.19.75+ #1270 Tue Sep 24 18:38:54 BST 2019 armv6l GNU/Linux
```

**Comment by mrjackyliang** [comment] 2019-10-22 16:19
Ah, got it. Working on that issue now. Thanks!

**Comment by jlclarkrx** [comment] 2019-10-26 17:10
I have this same issue as well:
Homebridge: Version 0.4.50
node: v10.16.0
Linux hoobs 4.19.50-v7+ #896 SMP Thu Jun 20 16:11:44 BST 2019 armv7l GNU/Linux

**Comment by mrjackyliang** [comment] 2019-10-27 17:24
Hey all! I believe I may have fixed the issue with the latest update (`v1.2.3`), but I'm not completely sure since I don't have a Raspberry Pi handy.

Let me know if it works for you. If not, I might need some assistance. Thanks!

**Comment by jlclarkrx** [comment] 2019-10-27 17:43
I am still getting the same error after upgrading to v1.2.3. Thank you so much for trying though and your work on this plugin. This is the #1 reason I looked into homebridge.

**Comment by mrjackyliang** [comment] 2019-10-27 17:50
Got it, thanks for the compliment @jlclarkrx! 

Would it be possible for you to email me at contact@jackyliang.me? I would like to have you replace a file from the plugin, then reply me the log responses, so I know what's going on.

It's my best chance in fixing this bug since I don't utilize Hoobs or any arm processor hardware.

**Comment by mrjackyliang** [comment] 2019-10-27 22:19
So I managed to get Raspbian installed on my Mac, and came down to this issue. Apparently, the entire `response` array is undefined, but still trying to find out why.

<img width="801" alt="raspbian" src="https://user-images.githubusercontent.com/9779803/67642838-3bbe3b00-f8e6-11e9-802d-95dce64e7574.png">

**Comment by mrjackyliang** [comment] 2019-10-28 14:44
__Just giving you a quick update that I've found the problem__, and will implementing the fix within a few hours. I will briefly document the issue here for future reference:

The reason why the `response.request.path` failed initially, was because [ADT Pulse](https://portal.adtpulse.com) preferred a weaker [DH key](https://en.wikipedia.org/wiki/Diffie–Hellman_key_exchange) (possibly due to compatibility reasons), where OpenSSL `v1.1.1` openly declined DH key lower than 2048 bits.

So I did a [scan of the ADT portal's website](https://www.ssllabs.com/ssltest/analyze.html?d=portal.adtpulse.com), and found a list of TLS keys the server was willing to accept and came down with two cipher suites that did not compromise the security of this plugin:

| Original Cipher Suite                 | OpenSSL Variant             |
|---------------------------------------|-----------------------------|
| `TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384` | `ECDHE-RSA-AES256-GCM-SHA384` |
| `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` | `ECDHE-RSA-AES128-GCM-SHA256` |

The other two cipher suites (namely `TLS_DHE_RSA_WITH_AES_256_GCM_SHA384`, and `TLS_DHE_RSA_WITH_AES_128_GCM_SHA256`) were ommitted because they had a weak DH key that OpenSSL was complaining about.

I'll be testing the next version, and will let you know when the release is out! Thanks for your patience!

**Comment by mrjackyliang** [comment] 2019-10-28 15:10
The update `v1.2.4` is out now! Closing this issue.

**Closed by mrjackyliang** 2019-10-28 15:10 UTC
Labels: help wanted

**Comment by frnhgt** [comment] 2019-10-28 15:49
Thanks!  Confirmed all good in my setup.

**Comment by superfeldy** [comment] 2019-10-29 21:09
Working for me too! Thanks
