### ISSUE TITLE
[Support]: Invalid Platform

### ISSUE THREAD

**Issue by DanLysk** [mrjackyliang/homebridge-adt-pulse#136] opened 2024-02-02 18:46 UTC
### Pre-check confirmation

- [X] I am currently sponsoring you or have heavily contributed to this project.
- [X] I have kept the original title prefix, __"[Support]: "__

### Tell me exactly what happened

Hi there, I am receiving this error in Homekit. I checked the config and it looks good to me. 

![CapturFiles_8](https://github.com/mrjackyliang/homebridge-adt-pulse/assets/100032956/e829c7c9-008c-4859-8393-3e9eaca6295a)

### Logs relevant to this issue

```Shell
[30/01/2024, 17:23:42] [ADT Pulse] Initializing ADTPulse platform...
[30/01/2024, 17:23:42] [ADT Pulse] Plugin is unable to initialize due to an invalid platform configuration.
[30/01/2024, 17:23:42] [ADT Pulse] If you just upgraded from v2 to v3 / v3.1, please update your configuration structure.
[
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "options"
    ],
    "message": "Required"
  }
]
[30/01/2024, 17:23:42] [ADT Pulse] Configuring cached accessory for ADT Pulse Gateway (id: adt-device-0, uuid: f0a67cd8-a143-4992-ba09-e39b8c3955d4) ...
[30/01/2024, 17:23:42] [ADT Pulse] Configuring cached accessory for Security Panel (id: adt-device-1, uuid: af79de8a-2216-49c1-aafa-606251d39c3e) ...
[30/01/2024, 17:23:42] [ADT Pulse] Configuring cached accessory for Front Door (id: adt-device-14, uuid: 3c5348fb-021b-4785-8916-4a50d1319cea) ...
[30/01/2024, 17:23:42] [ADT Pulse] Configuring cached accessory for Garage Door (id: adt-device-16, uuid: f598ec0c-4e65-4137-bae1-b065cd06c0f6) ...
[30/01/2024, 17:23:42] [ADT Pulse] Configuring cached accessory for Back Door (id: adt-device-15, uuid: 3d1bd248-358c-4ef9-8ae8-f3564643fab0) ...
[30/01/2024, 17:23:42] [ADT Pulse] Configuring cached accessory for Alarm Ringing (id: adt-device-1-switch, uuid: e664d49d-7c11-4368-9403-d4d632c6a97e) ...
[02/02/2024, 11:54:58] [ADT Pulse] Initializing ADTPulse platform...
[02/02/2024, 11:54:58] [ADT Pulse] Plugin is unable to initialize due to an invalid platform configuration.
[02/02/2024, 11:54:58] [ADT Pulse] If you just upgraded from v2 to v3 / v3.1, please update your configuration structure.
[
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "options"
    ],
    "message": "Required"
  }
]
[02/02/2024, 11:54:58] No plugin was found for the platform "EufySecurity" in your config.json. Please make sure the corresponding plugin is installed correctly.
[02/02/2024, 11:54:58] Loading 3 accessories...
[02/02/2024, 11:54:59] [ADT Pulse] Configuring cached accessory for ADT Pulse Gateway (id: adt-device-0, uuid: f0a67cd8-a143-4992-ba09-e39b8c3955d4) ...
[02/02/2024, 11:54:59] [ADT Pulse] Configuring cached accessory for Security Panel (id: adt-device-1, uuid: af79de8a-2216-49c1-aafa-606251d39c3e) ...
[02/02/2024, 11:54:59] [ADT Pulse] Configuring cached accessory for Front Door (id: adt-device-14, uuid: 3c5348fb-021b-4785-8916-4a50d1319cea) ...
[02/02/2024, 11:54:59] [ADT Pulse] Configuring cached accessory for Garage Door (id: adt-device-16, uuid: f598ec0c-4e65-4137-bae1-b065cd06c0f6) ...
[02/02/2024, 11:54:59] [ADT Pulse] Configuring cached accessory for Back Door (id: adt-device-15, uuid: 3d1bd248-358c-4ef9-8ae8-f3564643fab0) ...
[02/02/2024, 11:54:59] Failed to find plugin to handle accessory Backyard
[02/02/2024, 11:54:59] Removing orphaned accessory Backyard
[02/02/2024, 11:54:59] Failed to find plugin to handle accessory Backyard
[02/02/2024, 11:54:59] Removing orphaned accessory Backyard
[02/02/2024, 11:54:59] Failed to find plugin to handle accessory Foyer
[02/02/2024, 11:54:59] Removing orphaned accessory Foyer
[02/02/2024, 11:54:59] Failed to find plugin to handle accessory Bicycle Room 
[02/02/2024, 11:54:59] Removing orphaned accessory Bicycle Room 
[02/02/2024, 11:54:59] Failed to find plugin to handle accessory Cat room
[02/02/2024, 11:54:59] Removing orphaned accessory Cat room
[02/02/2024, 11:54:59] [ADT Pulse] Configuring cached accessory for Alarm Ringing (id: adt-device-1-switch, uuid: e664d49d-7c11-4368-9403-d4d632c6a97e) ...
[02/02/2024, 11:59:58] [ADT Pulse] Initializing ADTPulse platform...
[02/02/2024, 11:59:58] [ADT Pulse] Plugin is unable to initialize due to an invalid platform configuration.
[02/02/2024, 11:59:58] [ADT Pulse] If you just upgraded from v2 to v3 / v3.1, please update your configuration structure.
[
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "options"
    ],
    "message": "Required"
  }
]
[02/02/2024, 11:59:59] [ADT Pulse] Configuring cached accessory for ADT Pulse Gateway (id: adt-device-0, uuid: f0a67cd8-a143-4992-ba09-e39b8c3955d4) ...
[02/02/2024, 11:59:59] [ADT Pulse] Configuring cached accessory for Security Panel (id: adt-device-1, uuid: af79de8a-2216-49c1-aafa-606251d39c3e) ...
[02/02/2024, 11:59:59] [ADT Pulse] Configuring cached accessory for Front Door (id: adt-device-14, uuid: 3c5348fb-021b-4785-8916-4a50d1319cea) ...
[02/02/2024, 11:59:59] [ADT Pulse] Configuring cached accessory for Garage Door (id: adt-device-16, uuid: f598ec0c-4e65-4137-bae1-b065cd06c0f6) ...
[02/02/2024, 11:59:59] [ADT Pulse] Configuring cached accessory for Back Door (id: adt-device-15, uuid: 3d1bd248-358c-4ef9-8ae8-f3564643fab0) ...
[02/02/2024, 11:59:59] [ADT Pulse] Configuring cached accessory for Alarm Ringing (id: adt-device-1-switch, uuid: e664d49d-7c11-4368-9403-d4d632c6a97e) ...
[02/02/2024, 12:16:16] [ADT Pulse] Initializing ADTPulse platform...
[02/02/2024, 12:16:16] [ADT Pulse] Plugin is unable to initialize due to an invalid platform configuration.
[02/02/2024, 12:16:16] [ADT Pulse] If you just upgraded from v2 to v3 / v3.1, please update your configuration structure.
[
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "options"
    ],
    "message": "Required"
  }
]
[02/02/2024, 12:16:17] [ADT Pulse] Configuring cached accessory for ADT Pulse Gateway (id: adt-device-0, uuid: f0a67cd8-a143-4992-ba09-e39b8c3955d4) ...
[02/02/2024, 12:16:17] [ADT Pulse] Configuring cached accessory for Security Panel (id: adt-device-1, uuid: af79de8a-2216-49c1-aafa-606251d39c3e) ...
[02/02/2024, 12:16:17] [ADT Pulse] Configuring cached accessory for Front Door (id: adt-device-14, uuid: 3c5348fb-021b-4785-8916-4a50d1319cea) ...
[02/02/2024, 12:16:17] [ADT Pulse] Configuring cached accessory for Garage Door (id: adt-device-16, uuid: f598ec0c-4e65-4137-bae1-b065cd06c0f6) ...
[02/02/2024, 12:16:17] [ADT Pulse] Configuring cached accessory for Back Door (id: adt-device-15, uuid: 3d1bd248-358c-4ef9-8ae8-f3564643fab0) ...
[02/02/2024, 12:16:17] [ADT Pulse] Configuring cached accessory for Alarm Ringing (id: adt-device-1-switch, uuid: e664d49d-7c11-4368-9403-d4d632c6a97e) ...
[02/02/2024, 12:20:52] [ADT Pulse] Initializing ADTPulse platform...
[02/02/2024, 12:20:52] [ADT Pulse] Plugin is unable to initialize due to an invalid platform configuration.
[02/02/2024, 12:20:52] [ADT Pulse] If you just upgraded from v2 to v3 / v3.1, please update your configuration structure.
[
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "options"
    ],
    "message": "Required"
  }
]
[02/02/2024, 12:26:52] [ADT Pulse] Initializing ADTPulse platform...
[02/02/2024, 12:26:52] [ADT Pulse] Plugin is unable to initialize due to an invalid platform configuration.
[02/02/2024, 12:26:52] [ADT Pulse] If you just upgraded from v2 to v3 / v3.1, please update your configuration structure.
[
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "options"
    ],
    "message": "Required"
  }
]
[02/02/2024, 12:27:48] [ADT Pulse] Initializing ADTPulse platform...
[02/02/2024, 12:27:48] [ADT Pulse] Plugin is unable to initialize due to an invalid platform configuration.
[02/02/2024, 12:27:48] [ADT Pulse] If you just upgraded from v2 to v3 / v3.1, please update your configuration structure.
[
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "options"
    ],
    "message": "Required"
  }
]
[02/02/2024, 12:29:10] [ADT Pulse] Initializing ADTPulse platform...
[02/02/2024, 12:29:10] [ADT Pulse] Plugin is unable to initialize due to an invalid platform configuration.
[02/02/2024, 12:29:10] [ADT Pulse] If you just upgraded from v2 to v3 / v3.1, please update your configuration structure.
[
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "options"
    ],
    "message": "Required"
  }
]
[02/02/2024, 12:31:40] [ADT Pulse] Initializing ADTPulse platform...
[02/02/2024, 12:31:40] [ADT Pulse] Plugin is unable to initialize due to an invalid platform configuration.
[02/02/2024, 12:31:40] [ADT Pulse] If you just upgraded from v2 to v3 / v3.1, please update your configuration structure.
[
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "options"
    ],
    "message": "Required"
  }
]
[02/02/2024, 12:33:47] [ADT Pulse] Initializing ADTPulse platform...
[02/02/2024, 12:33:47] [ADT Pulse] Plugin is unable to initialize due to an invalid platform configuration.
[02/02/2024, 12:33:47] [ADT Pulse] If you just upgraded from v2 to v3 / v3.1, please update your configuration structure.
[
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "options"
    ],
    "message": "Required"
  }
]
[02/02/2024, 12:38:20] [ADT Pulse] Initializing ADTPulse platform...
[02/02/2024, 12:38:20] [ADT Pulse] Plugin is unable to initialize due to an invalid platform configuration.
[02/02/2024, 12:38:20] [ADT Pulse] If you just upgraded from v2 to v3 / v3.1, please update your configuration structure.
[
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "options"
    ],
    "message": "Required"
  }
]
[02/02/2024, 12:40:01] [ADT Pulse] Initializing ADTPulse platform...
[02/02/2024, 12:40:02] [ADT Pulse] Plugin is unable to initialize due to an invalid platform configuration.
[02/02/2024, 12:40:02] [ADT Pulse] If you just upgraded from v2 to v3 / v3.1, please update your configuration structure.
[
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "options"
    ],
    "message": "Required"
  }
]
[02/02/2024, 12:41:49] [ADT Pulse] Initializing ADTPulse platform...
[02/02/2024, 12:41:49] [ADT Pulse] Plugin is unable to initialize due to an invalid platform configuration.
[02/02/2024, 12:41:49] [ADT Pulse] If you just upgraded from v2 to v3 / v3.1, please update your configuration structure.
[
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "options"
    ],
    "message": "Required"
  }
]
[02/02/2024, 12:42:37] [ADT Pulse] Initializing ADTPulse platform...
[02/02/2024, 12:42:37] [ADT Pulse] Plugin is unable to initialize due to an invalid platform configuration.
[02/02/2024, 12:42:37] [ADT Pulse] If you just upgraded from v2 to v3 / v3.1, please update your configuration structure.
[
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "options"
    ],
    "message": "Required"
  }
]
[02/02/2024, 12:42:37]	[EufySecurity]	WARN	warning: planned changes, see https://github.com/homebridge-eufy-security/plugin/issues/1
[02/02/2024, 12:42:37]	[EufySecurity]	INFO	ffmpegPath set: /var/lib/homebridge/node_modules/homebridge-eufy-security/node_modules/ffmpeg-for-homebridge/ffmpeg
[02/02/2024, 12:42:37]	[EufySecurity]	INFO	Country set: US
[02/02/2024, 12:42:37]	[EufySecurity]	INFO	Finished initializing!
[02/02/2024, 12:42:37] Loading 3 accessories...
[02/02/2024, 12:44:14] [ADT Pulse] Initializing ADTPulse platform...
[02/02/2024, 12:44:14] [ADT Pulse] Plugin is unable to initialize due to an invalid platform configuration.
[02/02/2024, 12:44:14] [ADT Pulse] If you just upgraded from v2 to v3 / v3.1, please update your configuration structure.
[
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "options"
    ],
    "message": "Required"
  }
]
```

### Legal Agreements

- [X] I agree to the Terms of Use and Privacy Policy

**Comment by mrjackyliang** [comment] 2024-02-02 19:13
Duplicate of #132

**Closed by mrjackyliang** 2024-02-02 19:14 UTC
Labels: question
