### ISSUE TITLE
Sensors Disappear after ADT Pulse had its Home View Feature Removed

### ISSUE THREAD

**Issue by knedd** [mrjackyliang/homebridge-adt-pulse#22] opened 2020-03-19 02:52 UTC
### Describe the bug:
A recent upgrade to the Homebridge application to 0.4.53 seems to be impacted by the deprecation of request. To the extent accessories, other than the security panel, no longer appear in Homebridge when using the Homebridge-adt-pulse plugin.

**Comment by mrjackyliang** [comment] 2020-03-19 04:41
Bug acknowledged. It happened to me around 2 pm EST. Working on that bug!

**Comment by mrjackyliang** [comment] 2020-03-21 04:31
The issue is fixed, and update `v1.8.1` is available.

If there are missing accessories, please comment on the _actual_ device names listed on __ADT Pulse__ and the type of sensor.

**Comment by Glitch482** [comment] 2020-03-21 20:33
Running v1.8.2 and no sensors are appearing, also getting "null" on the zone listing link.

**Comment by knedd** [comment] 2020-03-21 20:38
I am running 1.8.2 and my sensors are all reporting ok. 

Kevin

Sent via iPhone

**Comment by Glitch482** [comment] 2020-03-21 21:02
Restored an earlier backup (v1.8.0) just to see what happens, and the logs show the sensors being removed. No luck updating to v1.8.2. 

[3/21/2020, 1:54:57 PM] [ADT-Pulse] Preparing to remove zone (sensor-14) accessory...
[3/21/2020, 1:54:57 PM] [ADT-Pulse] Removing accessory... UPSTAIRS HALLWAY SMOKE (sensor-14)
[3/21/2020, 1:54:58 PM] [ADT-Pulse] Preparing to remove zone (sensor-28) accessory...
[3/21/2020, 1:54:58 PM] [ADT-Pulse] Removing accessory... UPSTAIRS GUESTRM WIN (sensor-28)
[3/21/2020, 1:54:58 PM] [ADT-Pulse] Preparing to remove zone (sensor-20) accessory...
[3/21/2020, 1:54:58 PM] [ADT-Pulse] Removing accessory... TV RM WIN 2 (sensor-20)
[3/21/2020, 1:54:58 PM] [ADT-Pulse] Preparing to remove zone (sensor-19) accessory...
[3/21/2020, 1:54:58 PM] [ADT-Pulse] Removing accessory... TV RM WIN 1 (sensor-19)
[3/21/2020, 1:54:58 PM] [ADT-Pulse] Preparing to remove zone (sensor-30) accessory...
[3/21/2020, 1:54:58 PM] [ADT-Pulse] Removing accessory... STAIRWAY HALLWAY WIN (sensor-30)
[3/21/2020, 1:54:58 PM] [ADT-Pulse] Preparing to remove zone (sensor-25) accessory...
[3/21/2020, 1:54:58 PM] [ADT-Pulse] Removing accessory... OUTSIDE GAR DR (sensor-25)
[3/21/2020, 1:54:58 PM] [ADT-Pulse] Preparing to remove zone (sensor-18) accessory...
[3/21/2020, 1:54:58 PM] [ADT-Pulse] Removing accessory... MUSIC RM WIN (sensor-18)
[3/21/2020, 1:54:58 PM] [ADT-Pulse] Preparing to remove zone (sensor-29) accessory...
[3/21/2020, 1:54:58 PM] [ADT-Pulse] Removing accessory... LIV RM MOTION (sensor-29)
[3/21/2020, 1:54:58 PM] [ADT-Pulse] Preparing to remove zone (sensor-23) accessory...
[3/21/2020, 1:54:58 PM] [ADT-Pulse] Removing accessory... KITCHEN NOOK (sensor-23)
[3/21/2020, 1:54:58 PM] [ADT-Pulse] Preparing to remove zone (sensor-26) accessory...
[3/21/2020, 1:54:58 PM] [ADT-Pulse] Removing accessory... GAR DR RLL UP1 (sensor-26)
[3/21/2020, 1:54:58 PM] [ADT-Pulse] Preparing to remove zone (sensor-27) accessory...
[3/21/2020, 1:54:58 PM] [ADT-Pulse] Removing accessory... GAR DR RLK UP2 (sensor-27)
[3/21/2020, 1:54:58 PM] [ADT-Pulse] Preparing to remove zone (sensor-17) accessory...
[3/21/2020, 1:54:58 PM] [ADT-Pulse] Removing accessory... FRONT DR (sensor-17)
[3/21/2020, 1:54:58 PM] [ADT-Pulse] Preparing to remove zone (sensor-24) accessory...
[3/21/2020, 1:54:58 PM] [ADT-Pulse] Removing accessory... DOWNSTAIRS BATH WIN (sensor-24)
[3/21/2020, 1:54:58 PM] [ADT-Pulse] Preparing to remove zone (sensor-21) accessory...
[3/21/2020, 1:54:58 PM] [ADT-Pulse] Removing accessory... DINING RM WIN (sensor-21)
[3/21/2020, 1:54:58 PM] [ADT-Pulse] Preparing to remove zone (sensor-22) accessory...
[3/21/2020, 1:54:58 PM] [ADT-Pulse] Removing accessory... DINING RM SLIDER (sensor-22)


> 
> I am running 1.8.2 and my sensors are all reporting ok. Kevin Sent via iPhone
> […](#)
> On Mar 21, 2020, at 4:33 PM, Glitch482 ***@***.***> wrote: ﻿ Running v1.8.2 and no sensors are appearing, also getting "null" on the zone listing link. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mrjackyliang** [comment] 2020-03-21 21:23
@Glitch482 The reason why the sensors don't show up for you is because the sensor names are irregular.

This is something that is changed, because the old zone listing link included zone types, and the new scraper I built does not (ADT doesn't provide this information anymore).

This issue is easy to fix.

First, log on to the __ADT Pulse Portal > System__ and take a screenshot of all the devices you have.

That list should include the names and zone numbering information where I can use my best guess to figure out what kind of sensor it is.

And then I will update the plugin (will LYK), so your sensors will be added back.

Just word of note though, you will need to set all the accessories up again (annoying, but I did mines just this morning).

And if you can, try to save screenshots of your setup and back up with Homebridge cause I feel like the next few months of ADT Pulse are going to be rough.

**Comment by Glitch482** [comment] 2020-03-21 21:58
Sure, here's a screenshot of the devices

![system](https://user-images.githubusercontent.com/57071922/77237321-7a4dde00-6b84-11ea-9f82-9960e2a07875.JPG)

**Comment by mrjackyliang** [comment] 2020-03-21 22:38
@Glitch482 Hmm... working on that. Although, kind of wondering what the Kitchen Nook is... is that always going to be a door/window sensor?

**Comment by Glitch482** [comment] 2020-03-21 22:59
It’s a window sensor, staying that way.

**Comment by mrjackyliang** [comment] 2020-03-21 23:00
Cool, working on it.

**Comment by mrjackyliang** [comment] 2020-03-21 23:35
@Glitch482 You may now update to `v1.8.4`. Should include all the accessories from the screenshot you sent.

**Comment by Glitch482** [comment] 2020-03-21 23:42
Everything is back, thanks! 
> 
> 
> @Glitch482 You may now update to `v1.8.4`. Should include all the accessories from the screenshot you sent.

**Comment by Glitch482** [comment] 2020-03-25 02:36
> 
> And if you can, try to save screenshots of your setup and back up with Homebridge cause I feel like the next few months of ADT Pulse are going to be rough.

ADT pulse stopped responding tonight, this may be the start.

**Comment by mrjackyliang** [comment] 2020-03-25 02:39
@Glitch482 It could possibly be a coincidence that when you attempt to arm/disarm that the website logged you out.

Just tried it, it works.

**Comment by Glitch482** [comment] 2020-03-25 02:50
> 
> 
> @Glitch482 It could possibly be a coincidence that when you attempt to arm/disarm that the website logged you out.
> 
> Just tried it, it works.

Found the issue on my end, somehow the config.json entry got borked. Thanks for pointing me in the right direction!

**Comment by mrjackyliang** [comment] 2020-03-30 22:13
It looks like there aren't any requests related to the name change, so I'll be closing this issue!

**Comment by mrjackyliang** [comment] 2020-06-04 12:33
@sptv1 You may send in a screenshot of your ADT sensors here. To get a list of the sensors, login to ADT Pulse and click __System__ or [click this link](https://portal.adtpulse.com/myhome/19.0.0-89/system/system.jsp)

**Closed** 2020-06-09 18:34 UTC
Labels: bug

**Comment by mrjackyliang** [comment] 2020-07-21 22:57
@Glitch482 Just FYI, the "KITCHEN NOOK" window sensor detection may be removed in the future, because there is a named conflict with another user having a `Z41 Nook Glass Detector` and it is being detected as a contact sensor.

If possible, please call ADT to have a technician re-program the name to appear as "KITCHEN NOOK WIN".

**Comment by mrjackyliang** [comment] 2021-03-07 01:48
`v2.0.0` has just been released, and adds support for allowing users to manually override auto-detected sensors.

@Glitch482, @w1llf0rd, @tjclayton - Bringing this attention to you because `v2.0.0` will stop supporting the hard-coded sensors that were implemented for you pre `v2.0.0`. You may also configure this in the Homebridge UI.

**Comment by tjclayton** [comment] 2021-03-15 15:02
Thanks for letting me know. I appreciate it.
