### ISSUE TITLE
ADT Pulse Canada Support

### ISSUE THREAD

**Issue by geoffreyspencer** [mrjackyliang/homebridge-adt-pulse#37] opened 2020-08-22 16:53 UTC
### Describe the bug:
ADT Pulse not working in Canada

### Steps to reproduce the bug:
1. I cannot log-in because the plug-in is using the U.S. ADT Pulse site. I need to use the Canadian ADT Pulse site: https://portal-ca.adtpulse.com (note the -ca)

### Expected behavior:
I would be able to log in to my ADT Pulse using the Canadian ADT Pulse service

### The Apple device you are using:
- Device: [e.g. iPhone 11 Pro]
- OS: [e.g. iOS 13.3]

### Homebridge information:
Find these 4 lines in the beginning of the logs, then replace the text inside the grave accents:

```sh
[1/1/2020, 0:00:00 PM] [ADT Pulse] running on iMac (Intel - 64-bit)
[1/1/2020, 0:00:00 PM] [ADT Pulse] homebridge-adt-pulse v1.0.0
[1/1/2020, 0:00:00 PM] [ADT Pulse] node v12.13.0
[1/1/2020, 0:00:00 PM] [ADT Pulse] homebridge v0.4.50
```

I downloaded your code. I added another option to the configuration to select your country (U.S. or Canada). I updated the api.js to accept the country and updated the script to use either portal.adtpulse.com for U.S. or portal-ca.adtpulse.com for Canada. It needs to be tested. How do I get the code back to you for review, testing and publishing?

**Comment by geoffreyspencer** [comment] 2020-08-25 20:19
Sorry. Had issues at work that needed to be resolved first. Where on the macOS system are the plug-in files like api.js for this ADT plug-in? I found /Users/<myname>/.homebridge but there are no plug-in scripts there. Thanks.

**Comment by mrjackyliang** [comment] 2020-08-25 23:02
Thank you! Let me know if all the tests work and I'll implement the changes!

**Comment by geoffreyspencer** [comment] 2020-08-25 23:06
Okay. Only one thing is not working and that is the motion sensor are being tripped but nothing is showing up in the Home app or in the Homebridge console log. I do see the trigger in the ADT portal. The doors' triggers are working. Not sure how to test the smoke detectors. The panel is working. I do not have a Home setting but Away, Stay and Off/Disarmed so I do not know what that state would do to the panel. Maybe nothing.

**Comment by mrjackyliang** [comment] 2020-08-25 23:15
As far as I know, you're using the same version as the one used in the US.

When you do these tests, enable Test Mode in the ADT website. This prevents authorities from being called for the time being.

And Home is pretty much Arm Stay. That's how they say it in the Home app😁

**Comment by mrjackyliang** [comment] 2020-08-25 23:17
Also, for the motion sensors, it is all of them that has this issue?

**Comment by geoffreyspencer** [comment] 2020-08-26 09:41
Most of the sensors are working. It took a while but the sensors are reporting motion triggered now. Just not when they first appeared in the HomeBridge and the Home app. Weird. Is there a way to get specific type of arming when creating automation? I would like to get away triggered and night/stay triggered to behave differently. Away, turn off ALL the lights. Night, turn off the lights except for the bedrooms. I only see Armed trigger yet the Home app displays the type of arming that was selected.

**Comment by mrjackyliang** [comment] 2020-08-26 12:14
Possibly the delay was caused by a HomeKit network issue. This frequently happens on mine after I started segregating the networks apart.

And yes. Advanced automations can be done through the use of Home+ app. I currently use it to build advanced automations!

**Comment by geoffreyspencer** [comment] 2020-08-28 18:26
Fun while it lasted. The portal works but the devices are no longer responding in HomeBridge. Shame. I had a whole bunch of automated scripts set up in Home+.

**Comment by mrjackyliang** [comment] 2020-08-28 19:09
Yeah, that sometimes happen with HomeKit. Should be some local network issues.

**Comment by mrjackyliang** [comment] 2020-08-29 20:51
I have some time tonight, going to update the plugin and then post the zip file here.

**Comment by mrjackyliang** [comment] 2020-09-12 14:08
ADT Pulse Canada is now supported with `v1.9.0`. Closing!

**Closed by mrjackyliang** 2020-09-12 14:08 UTC
Labels: enhancement
